claim/claimstore.go, utils/crud/filesystem.go
=> Cleanup string delimiters

bundle/parameters.go, bundle/parameters_test.go
=> Update paramters apply-to => applyTo.

bundle/bundle.go, bundle/bundle_test.go
See https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#schema-version
This is a race with #24, so depending on which goes first, this one or that will need to be updated. 😀
=> Add required schemaVersion field to bundle

bundle/definition/schema.go
Improve the logic of the boolean case in ConvertValue()
=> Small improvement to ConvertValue()

action/action.go, action/action_test.go
When the underlying bundle has not parameters `opFromClaim` crashes with a nil pointer dereference error. This PR fixes this issue and add a unit test to cover this case.
=> Fix a nil pointer dereference when running an action

brigade.js
* adds handling of issue comment events (`/brig run` currently)
Goes towards improvements/updates to CI as tracked in https://github.com/deislabs/cnab-go/issues/31
=> ci(brigade.js): add issue comment handler

brigade.js
* add individual check run handler
* general re-org
* add semicolons where expected
* ensure 2 space indent
Closes https://github.com/deislabs/cnab-go/issues/31
=> ci(brigade.js): general refresh/update

bundle/bundle.go, testdata/bundles/bundle.yaml
Closes https://github.com/deislabs/cnab-go/issues/105
=> fix(bundle.go): add omitempty to contentDigest yaml tag

action/action.go, action/action_test.go
Resolves https://github.com/deislabs/cnab-go/issues/86
=> Fixes bug where cnab-go was not marshaling params as json

action/action.go, action/action_test.go
- Fixes https://github.com/deislabs/cnab-go/issues/123 and duplicate issue in duffle repo: https://github.com/deislabs/duffle/issues/856
=> Insert bundle.json at /cnab/bundle.json

brigade.js
Signed-off-by: Vaughn Dice <vadice@microsoft.com>
=> chore(brigade.js): update org

CODEOWNERS
Thank you again for all the work, @youreddy!
=> Remove youreddy as core maintainer

action/action.go, action/action_test.go
* Updates the env vars on an operation per https://github.com/cnabio/cnab-spec/blob/master/400-claims.md#environment-variables
=> feat(action): update CNAB_* env vars

driver/docker/docker.go, driver/docker/docker_test.go, go.mod, go.sum
* Add ability to access the container/host config from a Docker driver
This is motivated by the desire to unit test in this area for runtimes that modify these configurations.
=> feat(docker.go): access Docker configuration options

utils/crud/backingstore.go
Only autoclose the crud store in a function when that function is the one that called Connect. This removes the burden from functions that call other functions that use a crud store from having to keep track of whether or not AutoClose is enabled.
This isn't used much currently, it improves `ReadAll`, but it will be much more useful in the new functions incoming for supporting the claims spec update.
=> Improve autoclose logic

bundle/definition/validation.go
This adds a `ValidateSchema` method to the `Schema` struct.  This will be handy for validating that the schema itself is well-formed and valid JSON Schema.
Essentially, we were already doing this schema validation, but only in the context of a value we wanted to validate against the schema.  Therefore, I wanted to break it apart for standalone use.  For instance, to validate a parameter definition at build time and when we have no value (default or otherwise) to validate with.
As follow-ups, I hope to utilize this new method when validating that the definition schemas for parameters and outputs in a bundle are valid JSON Schema.  (From there, we can actually validate that any supplied parameter or output defaults are valid per these validated schemas -- we'll have added these pieces in …
=> feat(validation.go): add ValidateSchema function

CODEOWNERS
=> Remove @glyn from codeowners

driver/docker/docker.go, driver/docker/docker_test.go
When set, DOCKER_NETWORK specifies the --net flag value to pass to docker when running an invocation image. This allows the user to connect to the host network, or another named network.
This is mostly useful when running bundles that want to connect to services that are running on a dev's local machine, such as a minikube cluster which usually are not publicly addressable or easily reached from a container on a different docker network.
=> Support DOCKER_NETWORK driver variable

Makefile, azure-pipelines.yml, e2e-kind.sh
Our CI was using ubuntu 16.04 which isn't supported anymore. This bumps the build image to just use the latest ubuntu image.
=> Bump the build image used

driver/kubernetes/kubernetes.go
When the runtime is streaming the logs from the invocation image running
in a pod on Kubernetes, we will inevitably start polling before the
container is ready. Do not print warnings about retrying streaming the
logs and instead only print an error if we are unable to stream the logs
and have used up our retry attempts.
Fixes #271
=> Do not log when we retry streaming pod logs

Makefile, golangci.yml, imagestore/ocilayout/testdata/artifacts/layout/index.json
=> Addressed failing pipeline
