cnabio/cnab-go

- bundle/bundle.go
- bundle/bundle_test.go
- testdata/bundles/foo.json
This adds the custom extensions section to Bundle from the CNAB Spec as part of the push to close gaps for 1.0. See https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-extensions from the CNAB Spec.
> Add custom extensions to bundle struct

- bundle/bundle.go
This is a follow-up to https://github.com/deislabs/cnab-go/pull/21/files#r289733051 to ensure that custom isn't serialized when empty.
> Add missing omitempty to Bundle.Custom

- action/action_test.go
- bundle/bundle.go
- bundle/bundle_test.go
- bundle/parameters.go
- bundle/parameters_test.go
The spec field for default parameter value change to `default` instead of `defaultValue`
Related deislabs/duffle#753
> Correct the `default` parameter value on bundle

- Gopkg.lock
- Gopkg.toml
- claim/claimstore.go
- utils/crud/filesystem.go
- utils/crud/mongodb.go
- utils/crud/mongodb_test.go
This adds a MongoDB backend for claims storage.
This is mainly intended to be an example of how to write claim storage backends.
> added mongodb as a claim storage backend.

- Gopkg.lock
- action/action_test.go
- bundle/bundle.go
- bundle/credentials.go
- bundle/credentials_test.go
- credentials/credentialset.go
- credentials/credentialset_test.go
Per the spec, credentials have more attributes than just location, so this PR changes the definition around. Originally, this was just adding the `required` field but we also didn't have description. 
Closes #27
> Updating credentials to use a struct with more than location

- action/action.go
- action/action_test.go
- bundle/bundle.go
- bundle/bundle_test.go
- bundle/outputs.go
- bundle/parameters.go
- bundle/parameters_test.go
This PR is the first step in updating cnab-go to match the spec with regard to Parameters and Outptus. The overall change is pretty large when you consider adding JSON Schema, so I'm opening this PR first and will do a follow-on with the JSON schema in the interest of making things easy to review. This PR specifically introduces an `outputs` section to the bundle definition with corresponding structs, and introduces both `fields` and `required` fields to the parameters definition. 
Part of #17 and #14
> Step One: Introduce Outputs and "Fields" and "Required" to Parameters

- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
This PR updates the README.md to remove the language about experimental-ness and the wording to not take a dependency on cnab-go. It also adds a CONTRIBUTING.md and a GOVERNANCE.md file, inspired by Porter and Duffle. 
It also defines release versioning / tagging. 
Closes #13 and #16
> Update README file

- bundle/definition/schema.go
- bundle/definition/schema_test.go
This PR re-introduces the ConvertValue(interface{}) method, but relocates it to
the definitions package.
The method was removed during the refactor since the types can be more than the simple types before, but was added back for convenience.  It only works on number, integer, boolean or string types. Others return an error.
> Reintroduce ConvertValue(interface{})

- action/action.go
- action/action_test.go
- bundle/bundle.go
- claim/claim.go
- claim/claim_test.go
- claim/claimstore_test.go
This PR start the solution for the issue: deislabs/duffle#785
> Add Image relocation Map to translate invocation image

- bundle/bundle.go
- bundle/bundle_test.go
bundle.ValuesOrDefaults failed with a panic due to a nil pointer dereference when no parameters are defined in the bundle passed to the function.
> Fix a nil pointer deference in bundle.ValuesOrDefaults

- driver/driver.go
- driver/driver_test.go
- testdata/operations/valid-operation.json
fixes #47.
@jeremyrickard , @silvin-lubecki this replace #48 , now has marshall/unmarshall tests
> exclude Out from json marshalling in Operation

- bundle/bundle.go
- bundle/bundle_test.go
This PR introduces a breaking change in the Bundle.ValuesOrDefaults function signature by taking a map of current parameter values in order to handle the recently introduced `immutable` field in the bundle parameters description.
The patch verifies when a parameter value is set:
1. the parameter has the immutable field set in the bundle
2. there is a previously set value for this parameter (i.e. a value has been set during the initial installation of the bundle) 
3. the new and existing values of this parameter are not identical
In that case an error is returned.
> Handle immutable parameters in Bundle.ValuesOrDefaults

- claim/claim.go
- claim/claim_test.go
- claim/claimstore_test.go
- add Outputs field to Claim struct, per cnab-spec (updated in https://github.com/deislabs/cnab-spec/pull/217)
> feat(claim.go): add Outputs field to Claim struct

- brigade.js
- adds an event handler for push events and if ref matches a semver tag, proceed with creation of a GH release
Closes https://github.com/deislabs/cnab-go/issues/61
> ci(brigade.js): add githubRelease handler

- claim/claim.go
- remove Files field from Claim struct
I couldn't find any use of this field and it doesn't appear to be a part of the [claims spec](https://github.com/deislabs/cnab-spec/blob/master/400-claims.md).
> chore(claim.go): remove unused Files field from Claim struct

- bundle/outputs.go
Path is required in an output definition, so this removes the omitEmpty tag
from the JSON/mapstructure business.
Fixes #69
> Remove omitEmpty from Outputs Path

- bundle/bundle.go
- bundle/bundle_test.go
- testdata/bundles/digest.json
This PR swaps `contentDigest` in place of `digest` in the json/mapstructure tags for the BaseImage type. Adds a test for marashalling as well.
Fixes #59
> Switch `digest` to `contentDigest` in the json tags

- driver/command/command_windows.go
Noticed this when I was updating Duffle.
> command-windows referenced old interface from duffle (CommandDriver)

- bundle/bundle.go
- bundle/bundle_test.go
- testdata/bundles/foo.json
- adds the `RequiredExtensions` string array field to the `Bundle` struct, per the CNAB Spec (added in https://github.com/deislabs/cnab-spec/pull/220)
Closes #71
> feat(bundle.go): add RequiredExtensions

- bundle/definition/schema.go
- bundle/definition/schema_test.go
Adds `yaml` tags to the `Schema` struct.  This change was motivated by the need by a third-party consumer ([porter](https://github.com/deislabs/porter)) to use this canonical `Schema` struct instead of its out-of-date, reduced subset version.  (See also https://github.com/deislabs/porter/issues/444)  Currently, Porter's manifest comes in the form of yaml, hence the need to properly unmarshal yaml into this struct.
Note that there are a few minor fixes here, as well:
- adds the `Schema`/`$schema` string field to the `Schema` struct, per https://json-schema.org/understanding-json-schema/reference/schema.html  (We'd been populating it previously, as seen in `schema_test.go`, but it wasn't yet part of the struct.)
- fixes copy/pasta for a few fields on their `mapstructure` tags: `id` and …
> feat(schema.go): add yaml tags to Schema struct

- Makefile
- README.md
- action/action.go
- action/action_test.go
- action/install.go
- action/install_test.go
- action/run_custom.go
- action/run_custom_test.go
- action/status.go
- action/status_test.go
- action/uninstall.go
- action/uninstall_test.go
- action/upgrade.go
- action/upgrade_test.go
- bundle/definition/schema.go
- bundle/definition/schema_test.go
- claim/claim.go
- driver/command/command.go
- driver/docker/docker.go
- driver/docker/docker_integration_test.go
- driver/driver.go
- driver/driver_test.go
- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
- driver/kubernetes/kubernetes_test.go
- testdata/bundles/example-outputs/build.sh
- testdata/bundles/example-outputs/bundle.json
- testdata/bundles/example-outputs/cnab/Dockerfile
- testdata/bundles/example-outputs/cnab/app/run
In pursuit of https://github.com/deislabs/duffle/issues/747
Fixes https://github.com/deislabs/cnab-go/issues/14 and fixes https://github.com/deislabs/cnab-go/issues/72
This PR:
- In action, if the driver gives you output files, put them in the claim.
- When adding output files to the claim, check that they match the definitions.
- Add Output support in Docker driver, and integration tests for same.
- Make K8s and Command drivers compile, but do not implement support.
cc @youreddy @jeremyrickard
> Add Outputs support to Docker Driver

- Makefile
- README.md
- azure-pipelines.yml
Test of pushing code coverage results to Azure Pipelines.
See https://dev.azure.com/deislabs/cnab-go/_build/results?buildId=2510&view=results
Readme now looks like:
The main reasons for trying this:
- we need code coverage results
- we are already using Azure Pipelines for this repo
That being said, I'm more than happy to look at other services for this (Coveralls, Codecov), although I haven't used them before - so suggestions are welcome :)
> Publish initial test coverage results to Azure Pipelines

- bundle/bundle.go
- bundle/credentials.go
- bundle/definition/schema.go
- bundle/outputs.go
- bundle/parameters.go
Represents a possible dual closing of https://github.com/deislabs/cnab-go/issues/91 and adding yaml tags to all of the structs (per recent history of third-party use in https://github.com/deislabs/cnab-go/pull/90 and https://github.com/deislabs/cnab-go/pull/92; 92 could/would be superseded by this PR.)
> ref(bundle/*): replace mapstructure tags with yaml tags

- driver/lookup/lookup.go
This transfers the `Lookup` method from [deislabs/duffle](https://github.com/deislabs/duffle/blob/master/pkg/driver/lookup.go) to this repo, in the continuing theme of moving generic/cnab-go-related logic into cnab-go itself (enabling third-party consumers to ideally only import cnab-go).
Assuming we merge, I can issue a follow-up PR in duffle to use this method from its new location here. (We should be able to delete duffle's entire [driver](https://github.com/deislabs/duffle/tree/master/pkg/driver) pkg in this case).
Note that I initially tried to add this `Lookup` method directly into `driver/driver.go`, but had to make extensive refactors to avoid cyclical imports (including creating a new package for the `Operation` and `OperationResult` structs currently in `driver.go`).  If we …
> feat(driver/lookup): add lookup pkg, Lookup method from duffle

- bundle/loader/loader.go
- bundle/loader/loader_test.go
Ports the `loader` pkg from duffle to this repo.
See associated duffle PR in https://github.com/deislabs/duffle/pull/832
> feat(bundle): add loader pkg from duffle

- credentials/credentialset.go
- credentials/credentialset_test.go
A credential has a `required` flag, which defaults to `true`. As #108 and the spec point out:
```
required indicates whether this credential MUST be supplied. By default it is false, which means the credential is optional. When true, a runtime MUST fail if the credential is not provided.
```
However, we were ALWAYS requiring any credential to have a value provided. This check occurred both in the CredentialSet Validate(..) method for that is used for stateful actions, but also the Expand(...) method. The Expand(..) method had an argument to flag an call to the method as stateless, in which case we allowed a credential to not be present but we still failed on optional for stateful calls. 
This PR adds explicit handling for optional credentials. 
Fixes #108
> Properly handle optional credentials

- driver/docker/docker.go
Update the docker driver to return early from fetchOutputs when there are no outputs defined on the operation. If there are none defined on the operation, there is a good chance /cnab/app/outputs won't exist and we _shouldn't_ try to copy from it in any case.  This is currently an issue in duffle (and I assume any other tools that have updated the dependency to pick this up), when no outputs are defined in the bundle. This simply adds a boundary condition check. 
If outputs _*are*_ set on the operation, we should continue and if it doesn't exist that is a failure case with that invocation image.
I think there is a related change we should make where we _only_ return the outputs defined on the operation. I think we are currently returning all the things in /cnab/app/outputs which is …
> Update the docker driver to return early from fetchOutputs

- bundle/bundle_test.go
- bundle/definition/schema.go
- bundle/definition/schema_test.go
All bundles are ultimately represented in canonical json format, which does not allow for decimal numbers, only integers. We are updating the specification to remove numbers from the schema and only allow for integers (see https://github.com/deislabs/cnab-spec/issues/256).
This updates our Schema struct to only use integers as well so that we can only represent valid bundles which can be written with the canonical json library that we use.
Closes #115
> Swap integer for float on the Schema struct

- CODEOWNERS
Pivotal's contributions for outputs in cnab-go and the Duffle driver were very important and they  have indicated they will continue to be involved in the spec, as well as Duffle and cnab-go development, so I'd like to nominate Urvashi  as a maintainer.
> Add Urvashi Reddy as a cnab-go maintainer

- CODEOWNERS
Matt Fisher has moved away from the CNAB project, so this PR removes him from the CODEOWNERS file. We thank you for your service @bacongobbler
> Removing Matt Fisher from CODEOWNERS

- claim/claim.go
- claim/claim_test.go
From the [docs](https://github.com/deislabs/cnab-spec/blob/cc78ad5f2f7f4fabce6247f02cafb786bc011e07/103-bundle-runtime.md#environment-variables):
> Installation names MUST consist of Graph Unicode characters and MAY be user-readable. The Unicode Graphic characters include letters, marks, numbers, punctuation, symbols, and spaces, from categories L, M, N, P, S, Zs.
This PR doesn't quite bring cnab-go up to spec, but does enable the use of installation names which include the `.` character (this supports our internal installation naming convention). If someone would like to school me in regex we can update this PR to be fully spec compliant. 😄
> Allow installation names including "." character

- bundle/definition/schema.go
- bundle/definition/validation.go
- bundle/definition/validation_test.go
- bundle/definition/validators.go
This represents a fix to ensure definitions with a non-empty `contentEncoding` property pass validation by adding a custom validator for continued use of the jsonschema library cnab-go currently uses.  It's specific to `contentEncoding` but illustrates a potential path forward for further "custom" validators (either for properties in the default JSON Schema but *not* stock in the jsonschema library or for truly custom properties/validators down the line.)
See https://github.com/deislabs/cnab-go/issues/117 for background on general issue and https://github.com/deislabs/porter/pull/579 for feature that uses the changes here to pass validation.
> fix(bundle/definition): add custom validator for contentEncoding

- driver/kubernetes/kubernetes.go
These are both often important bits of configuration which can vary depending on the Kubernetes environment.
> Support Pod annotations and node tolerations in Kubernetes Driver

- driver/docker/docker.go
Currently, it is hard to debug the state of an invocation image after
the various files and environment variables have been inserted by the
runtime. By not cleaning up the container, we allow bundle developers
an easier way to debug problems.
The parameter is CLEANUP_CONTAINERS, default is true. I decided to log some feedback if the value is incorrect. This is not what the other settings do, but seems user-friendly.
Fixes #128
cc @youreddy
> Add Docker driver config to keep container around

- packager/import.go
A bit of cleanup after this logic was imported from deislabs/duffle...
- removes unused custom error
- updates TODO issue URL
- removes unused `Verbose` struct field
- updates the `NewImporter` func signature to just return an `*Importer` object (had previously always returned `nil` for the additional `error` type)
> chore(packager/import.go): remove unused error, update issue location

- driver/kubernetes/kubernetes.go
Fix for the missing pod logs in the kubernetes driver.
We didn't check to make sure io.Copy() was writing anything, so sometimes it would finish before the pod actually wrote anything. Added a few checks to remedy this.
To reproduce bug:
Run `go test -tags=integration -count=20 ./driver/kubernetes`
See below fail at least once
> Fix for missing k8s logs

- driver/kubernetes/kubernetes.go
KUBECONFIG is the de facto standard environment variable for kubectl etc.
Without this change when the user omits KUBE_CONFIG, the default kube config
will be used, which may well point to a valid cluster, though this will
effectively be the wrong cluster when the user has set $KUBECONFIG.
This is a particular issue when kind (https://kind.sigs.k8s.io/) is used as
it doesn't update the default kube config.
> Rename k8s driver parm from KUBE_CONFIG to KUBECONFIG

- Makefile
- driver/command/command.go
- driver/command/command_nix_test.go
- driver/command/command_test.go
- driver/docker/docker_integration_test.go
Adds support for outputs to the command driver.
Command driver will create a temp folder for the driver process to write outputs to and pass the folder path to the driver process in the  environment variable CNAB_OUTPUT_DIR
fixes #84
> Add support for outputs to command driver

- bundle/bundle.go
- bundle/bundle_test.go
Adds a `DeepCopy` method on a `BaseImage` struct, used also for `DeepCopy` methods for the `InvocationImage` and `Image` structs.
> feat(bundle.go): add DeepCopy for InvocationImage/BaseImage/Image

- action/action.go
- action/action_test.go
Fixes https://github.com/deislabs/cnab-go/issues/133
> fix(action.go): only append an output to an operation if it applies to the action

- driver/kubernetes/kubernetes.go
This PR updates the Kubernetes driver to stream Pod logs when the Job which executes the invocation image has failed.
This allows end users to debug their invocation images if an action execution does not succeed.
> fix(kubernetes): print logs when job fails

- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
- driver/kubernetes/kubernetes_test.go
Long installation or action names currently cause the Kubernetes driver to fail because of character limits imposed by the platform ([63 chars for label values](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) and [253 chars for resource names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)).
This PR ensures that only valid DNS-1123 resource names less than the maximum length are generated, and uses annotations instead of labels for storing metadata about which jobs are associated with which operations.
> fix(kubernetes): handle long installation names

- brigade.js
The notifications sent by Brigade to GitHub around CI/check runs are failing due to https://github.com/brigadecore/brigade-github-app/issues/36
This PR disables appending the job logs to the notifications until 36 is resolved.
> fix(brigade.js): temp disable appending job logs to GH notification

- Makefile
- driver/kubernetes/kubernetes.go
* bumps golangci-lint version to latest
- this was motivated by seeing quite lengthy output in CI using the previous/outdated version, e.g. https://brigadecore.github.io/kashti/jobs/tests-01dvcyr1x6pk73cm2fh2v6h9xz.  It appears the bump eliminates this issue; see the test run here: https://brigadecore.github.io/kashti/jobs/tests-01dvedzvxfvn6beeb8k1r8a245
* addresses the following linting error seen locally:
```
$ make lint
golangci-lint run --config ./golangci.yml
driver/kubernetes/kubernetes.go:400:2: S1031: unnecessary nil check around range (gosimple)
if mergeWith != nil {
^
make: *** [lint] Error 1
```
> fix(*): bump golangci-lint; fix linting err

- .gitignore
- Makefile
- README.md
- azure-pipelines.yml
- credentials/testdata/staging-unix.yaml
- driver/kubernetes/kubernetes_integration_test.go
- e2e-kind.sh
This PR
- Runs docker and kubernetes driver integration tests (using [kind](https://github.com/kubernetes-sigs/kind) for kubernetes environment setup)
- Configures the azure pipeline to always report test results and coverage, even on failure
- Increases test code coverage in CI for the `driver/docker` package from 0% to 62%, and for `driver/kubernetes` from 21% to 68%.
See new coverage reporting here: https://dev.azure.com/deislabs/cnab-go/_build/results?buildId=4231&view=codecoverage-tab
> Execute integration tests in CI

- driver/docker/docker.go
Waiting container to stop is not working in old Docker API version(1.24).
In old Docker API version(1.24), before docker container started, `docker wait` will return immediately. In this case, `ContainerWait` function which creates a goroutine to wait container to stop, may send a message to  `statusc ` before container started, and this will make waiting container to stop fail.
Trying to wait container to stop after started container, and this will make waiting container work well.
Related source code:
[https://github.com/moby/moby/blob/1.12.x/container/state.go#L129](url)
> Waiting container to stop after started container, not before

- Makefile
- azure-pipelines.yml
- brigade.js
- go.mod
- go.sum
Upstream golang.org/x/sys introduced a breaking change within a major version again, see https://github.com/golang/go/issues/34610. The workaround is to pin it to the last revision that is compatible with moby/moby.
I've added builds for mac and windows to the CI run to verify the fix and catch problems more quickly in the future.
> Pin golang.org/x/sys to fix windows compilation

- driver/docker/docker.go
There was a regression introduced in #169 that I found when upgrading Porter to v0.8.0-beta1. This doesn't reproduce on every machine but it solidly reproduces every time Porter's build server unfortunately which has blocked me for a week tracking it down while we tried to upgrade to go mods and v0.8.0-beta1. 😅 
When the docker driver calls `ContainerWait` it doesn't always return now, causing that line of code to never exit and eventually hit our test timeouts.
<details>
<pre><code>
2020-01-09T16:18:48.0251089Z goroutine 671 [IO wait, 16 minutes]:
2020-01-09T16:18:48.0251320Z internal/poll.runtime_pollWait(0x7f0ff1197870, 0x72, 0xffffffffffffffff)
2020-01-09T16:18:48.0251578Z 	/usr/local/go1.13/src/runtime/netpoll.go:184 +0x55
2020-01-09T16:18:48.0251850Z …
> Regression waiting for container to stop, ContainerWait never returns

- credentials/credentialset.go
This allows tools to display when a credential set was created/modified without relying upon file timestamps which aren't available when credentials are stored in the generic crud datastore.
Since we have this data on Claim, it makes sense to have it on other data that we generally store in the host environment too.
Part of #172 
Signed-off-by: Carolyn Van Slyck <carolyn.vanslyck@microsoft.com>
> Add timestamps to CredentialSet

- claim/claimstore.go
- claim/claimstore_test.go
- utils/crud/filesystem.go
- utils/crud/filesystem_test.go
- utils/crud/mongodb.go
- utils/crud/store.go
- utils/crud/store_test.go
When a type's function is named the same as the type, the type cannot be embedded and satisfy an interface. By renaming Store.Store to Store.Save, we can embed a crud.Store in other types and have it satisfy an interface without having to fallback to type aliases.
Part of #172 
Signed-off-by: Carolyn Van Slyck <carolyn.vanslyck@microsoft.com>
> Rename Store.Store to Store.Save

- LICENSE
When the repository changed organizations, the license text wasn't updated.
This PR fixes that, and updates the license text to "The CNAB Authors".
> Change license text to "The CNAB Authors"

- credentials/credentialset.go
- credentials/credentialset_test.go
- credentials/testdata/staging-unix.yaml
- credentials/testdata/staging-windows.yaml
- secrets/host/host.go
- secrets/host/host_test.go
- secrets/store.go
Instead of having CredentialStrategy specific to retrieving credentials from a host, with hard-coded fields for command/path/env/value, live up to the "strategy" aspect and allow for other mechanisms of finding the credential value.
I have moved the resolution of credential values to a new subpackage secrets/host which implements a new interface secrets.Store. This allows for clients, like Porter, to use plugins to retrieve secret values from external systems such as Vault while still using CredentialSets.
One breaking change is that only a single source can be specified now without fallbacks. Since this functionality was very limited to begin with, you could only specify one env, and then could only fallback to a value, and only in that order, I'm unsure if we can preserve it. If we do, …
> Make CredentialStrategy generic

- claim/claimstore.go
- utils/crud/filesystem.go
- utils/crud/filesystem_test.go
- utils/crud/mongodb.go
- utils/crud/store.go
- utils/crud/store_test.go
CRUD can be used to work with any type of item, not just claims. Update the interface signature to support specifying what type of item is being stored so that the controlling code, e.g. the claim store or eventually a credential store, can say what type of data is being stored. For example "claims" or "credentials".
By altering the interface, this allows tools to avoid creating multiple instances of the same store to work with a different type of data.
Part of #172 
~🚨 This has some overlap with #174. I tried to make this PR independent but if that PR is merged first, this should be rebased and tweaked first.~ Rebase done.
> Update crud.Store to support general storage

- brigade.js
Re-enables sending job logs via GH Check Run notifications.
(Although https://github.com/brigadecore/brigade-github-app/issues/36 isn't fixed yet, we have confirmation that the job log length is back to a reasonable size as of https://github.com/cnabio/cnab-go/pull/164
> ci(brigade.js): re-enable sending check run logs

- bundle/bundle.go
- bundle/bundle_test.go
* Adds validation for the `Location` property (used by `Parameter`s and `Credential`s)
Implementation corresponding to proposed spec change in https://github.com/cnabio/cnab-spec/pull/330
> feat(bundle.go): add Location validation

- action/wellknown.go
- action/wellknown_test.go
When reviewing https://github.com/cnabio/cnab-go/pull/154 (albeit, tardily) I noticed what appeared to be remnants of a status+json well-known action.  I didn't see an implementation of the Action interface for this, so I assumed the remnants should just be removed.  Please advise if the opposite is true and we intend to add an implementation and offer it as a first-class well-known action.
> ref(action): remove status+json action

- claim/claim.go
- claim/claim_test.go
- claim/testdata/claim.default.json
* adds validation for the `Result` object, including its `Status` property, according to the [Claims Spec](https://github.com/cnabio/cnab-spec/blob/master/400-claims.md)
Note for reviewers:  Do we want to modify the function signature for the [Update](https://github.com/cnabio/cnab-go/blob/master/claim/claim.go#L85) method on a `Claim` to return an `error`?  We can then check to be sure the supplied `action` and `status` form a valid `Result`; if not, we would return an error.
> feat(claim): add Result validation

- action/action.go
- action/action_test.go
* Add the claim to the operation file list via `/cnab/claim.json` per https://github.com/cnabio/cnab-spec/blob/master/400-claims.md#files
> feat(action): add cnab/claim.json to op files

- bundle/bundle.go
- bundle/bundle_test.go
- bundle/credentials.go
- bundle/credentials_test.go
- bundle/parameters.go
- bundle/parameters_test.go
* adds Parameter and Credential validation, per spec
* validates both when validating a Bundle
* moved a few other validation functions closer to the structs they validate
> feat(bundle): add param and cred validation

- claim/claimstore.go
- claim/claimstore_test.go
- credentials/credstore.go
- credentials/credstore_test.go
- utils/crud/backingstore_test.go
- utils/crud/mock_store.go
- utils/crud/mock_store_test.go
* **Export crud.MockStore and allow mocking errors**
The MockStore struct is very useful for tests outside of the crud package, since it has an in-memory implementation of the crud.Store interface. This adds the ability to mock errors to test out how code that wrap the store handle edge cases and then exports the struct.
* **Improve matching of not found errors**
Previously in the claim and credential store, we matched exactly on the underlying not found errors from the crud store. This doesn't work well when the store may be being wrapped in layers, for example in Porter's case the store error is wrapped in an net/rpc error so the error doesn't match exactly.
This changes the matching to allow for how errors are usually wrapped, with an error message appended and the original message …
> Improve matching of not found errors 

- bundle/bundle.go
- bundle/bundle_test.go
* adds functionality in the `ValuesOrDefaults` method to skip parameter validation and value lookup if it does not apply to the provided action
* in doing so, updates the function signature to now pass in the action
> ref(bundle.go): only validate/return value if param applies to provided action

- driver/docker/docker.go
- driver/docker/docker_test.go
* update config fields on Driver struct to not be pointers
*  When consuming the latest code for use in Porter (to add tests around Porter's configuration options in this area), I found it problematic that some struct fields were pointers (`containerCfg` and `containerHostCfg`).  I started to go down the path of creating methods in this library to return default Driver objects (`NewDriver()` would return a `Driver` with initialized/empty field references) but then I realized perhaps the code simplifications and ease of use that came with switching the fields to be actual values would be warranted here.  What do reviewers think?  Is there Golang best practice w/r/t fields in structs being pointers?  (Avoid?  Only use if initializer method(s) are provided?)
* export …
> ref(docker.go): container config fields on Driver no longer pointers

- claim/claim.go
- claim/claim_test.go
* The entropy generator needs to be reused between ULIDs to ensure that each ULID is monotonically increasing.
* We should use the monotonic function so that ULIDs generated during the same millisecond can still be sorted.
* Use a mutex in ULID since math.Rand is not thread-safe.
I was seeing in unit tests where I was generating ULIDs back-to-back that they were not sorting correctly. After digging through the issue queue, it turns out the example on the README of the ulid library we use is not appropriate to copy and use. I believe this is what they recommend based on their replies to a few issues.
> Fix ULID generation

- azure-pipelines.yml
Azure Devops moved where new versions of go (1.11+) are installed and no longer recommends using the scripts we had for setting up go. They have a Task that they want you to use to pick the exact version of go you want and then use it to go get your code.
Our builds were failing because as part of this GOROOT moved from `/usr/local/go1.13` to `/usr/local/go1.13.PATCH` which since we don't actually specify patch, was a bit hard to intuit. 😅
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current#set-up-go
> Use GoTool Task

- action/install_test.go
- action/operation_configs_test.go
- action/run_custom_test.go
- action/uninstall_test.go
- action/upgrade_test.go
- bundle/bundle.go
- bundle/bundle_test.go
- claim/claimstore_test.go
- credentials/credentialset.go
- credentials/credentialset_test.go
- credentials/credstore_test.go
- driver/command/command_nix_test.go
- driver/docker/docker.go
- driver/docker/docker_test.go
- driver/driver.go
- driver/driver_test.go
- driver/kubernetes/kubernetes_test.go
- golangci.yml
- packager/export.go
- packager/import.go
- packager/import_test.go
The `goimports` settings in the linter options were wrong, meaning `goimports` was not running properly.
This PR fixes that, as well as the linter errors.
> Fix linter settings and errors

- Makefile
- azure-pipelines.yml
When you embed bash in yaml, make sure to stop on nonzero exit codes. Otherwise builds pass when they should have failed...
Signed-off-by: Carolyn Van Slyck <carolyn.vanslyck@microsoft.com>
> Stop on nonzero exit code

- Makefile
- azure-pipelines.yml
When I fixed adding go/bin to PATH, I accidentally moved instead of copied the lines to fail the script. Adding it back. 🤦‍♀️ 
So this does a check that I can yet again fail the build, and then fixes the installation of gocov, which isn't working on master, so we aren't publishing coverage results.
> Fail build take two

- claim/claimstore.go
- claim/claimstore_test.go
- claim/installation.go
- utils/crud/mock_store_test.go
Do not rely on inferring the names from the storage layer, e.g. the directory above the claims, that leaks the abstraction and makes implementing the store more difficult. Have the claim store be responsible for tracking the names of installed bundles explicitly.
I ran into this while implementing storage on top of object storage, where the installation wasn't encoded in the directory structure, but instead using tags on the objects. It just doesn't make sense to have to calculate what the installation names are at the crud.Store layer, when each implementation may be using a different technique.
> Store installation names

- claim/claimstore.go
- claim/claimstore_test.go
- utils/crud/backingstore.go
- utils/crud/backingstore_test.go
- utils/crud/mock_store.go
When the claimstore executes multiple queries against the crud store to execute a logical query, e.g. ReadInstallationStatus, ensure that it only results in a single call to Connect.
I've updated the claim store tests to use our MockStore so that we can assert on connects/closes. The MockStore was using nested maps that was hard to understand so I refactored it so it's easier to understand.
> Ensure a single connect per logical query

- action/action_test.go
- action/example_install_test.go
- action/example_invoke_test.go
- action/example_running_status_test.go
- action/example_upgrade_test.go
- claim/claimstore.go
- claim/claimstore_test.go
- claim/mock_store.go
- credentials/credstore.go
- credentials/credstore_test.go
- credentials/mock_store.go
- utils/crud/backingstore.go
Do not create backing stores internally for a claim or credential storage. Instead have the caller pass in the backing store so that the caller can control the lifetime and connection properties, such as AutoConnect, themselves.
For example, in porter this let's us use the same instance of a backing store independently and with a claim store, while keeping the connection open during the migration of the claims directory to match the new claims spec.
> Initialize storage from backing stores

- claim/claimstore.go
- claim/claimstore_test.go
When an output was removed, an error was generated listing the outputs for an installation:
```
could not determine if the output "user" is sensitive: output "user" not defined
```
After digging into the code where I traverse the last generated output value, I found that I was capturing the value of a for loop variable without first making it a local variable inside the for loop. Go doesn't do closures the same way other languages do, and what this really ended up doing was giving every instance the same reference. Not very useful.
> Fix error listing outputs when bundle definition changed

- claim/claimstore.go
- credentials/credstore.go
- utils/crud/backingstore.go
- utils/crud/backingstore_test.go
- utils/crud/filesystem.go
- utils/crud/filesystem_test.go
- utils/crud/mock_store.go
- utils/crud/mock_store_test.go
- utils/crud/mongodb.go
- utils/crud/store.go
* Define a new interface, `ManagedStore`, from BackingStore for types that wrap a datastore and manage the connection lifecycle. This will allow us to remove some of the nested levels of wrappers because we can implement the interface instead of having to pass in a specific type.
* Add Count to `crud.Store` which is part of ManagedStore. Count enables a CNAB tool to check if there exists any data of a specific type, e.g. Are there any claims?, without listing all the data. We are using this in Porter for data migrations around the Claim spec rewrite to help us test if we need to perform a migration.
> Extract ManagedStore interface from BackingStore

- utils/crud/filesystem.go
- utils/crud/filesystem_test.go
* Adds logic to remove the parent (group) directory if the item being deleted is the last one in that dir
Previously, group directories -- where a group is a named (ULID or installation name) directory under the item type directories of `claims`, `results` or `outputs` -- would linger after deleting an installation.
> fix(filesystem.go): also delete group directory

- credentials/credentialset.go
- credentials/credentialset_test.go
- credentials/testdata/staging-unix.yaml
- credentials/testdata/staging-windows.yaml
Add a schemaVersion field to credentialSet so that we can identify the spec version that the credential set adheres to. This was very useful for claims, we use it for data migrations when the claim spec changes, and it is best to have it _before_ we need to change the spec. Worst case we never change the spec again and we all win. 😄
The last change to the credential-set spec was https://github.com/cnabio/cnab-spec/releases/tag/cnab-credentialsets-1.0.0-DRAFT+b6c701f
> Add schemaVersion to credentialSet

- Makefile
- driver/docker/docker.go
- driver/docker/docker_integration_test.go
- driver/docker/docker_test.go
* Adds invocation image digest verification per the [CNAB Spec](https://github.com/cnabio/cnab-spec/blob/master/101-bundle-json.md#invocation-images) to the Docker driver.
The specific part of the spec that this PR currently implements is the following line:
`If a contentDigest field is present, a runtime MUST validate the image digest prior to executing an action.`
I didn't see how this would be done generically, e.g. outside of specific driver implementations, hence implementing it on the Docker driver only.  Am I right here?  If so, perhaps a follow-up could implement similar in the kubernetes driver.
Note some remaining TODOs/Qs inline.  Feel free to respond/answer in the form of code review comments.
> feat(docker): add verification of image digest(s)

- driver/docker/docker.go
- driver/docker/docker_integration_test.go
- driver/docker/docker_test.go
Bundles pushed with cnab-to-oci will have invocation images with more than one repoDigest, which is valid. One is for the original invocation image that was pushed. The other is for the relocated invocation image that is now inside the bundle repository.
https://porter.sh/distribute-bundles/#image-references-after-publishing
We should check all of the repoDigests and if a match is found, then it is valid.
This corrects a bug introduced in #227 that is present in [v0.14.0](https://github.com/cnabio/cnab-go/releases/tag/v0.14.0) where executing a bundle fail because bundles pushed with cnab-to-to-oci always have more than one repoDigest.
> Fix invocation image digest validation

- action/operation_configs.go
- action/operation_configs_test.go
- driver/command/command.go
- driver/docker/docker.go
- driver/docker/docker_integration_test.go
- driver/driver.go
Instead of writing by default to os.Stdout, the docker driver writes to op.Out and the new field op.Err. The op defaults those values to stdout/stderr, so if you weren't setting them previously the behavior is the same though errors are now sent to stderr instead of all lumped into stdout. But for tools like porter that were collecting the output, this enables them to capture all the output and not have rogue lines printed directly to the screen.
This doesn't remove containerOut/containerErr which Docker is relying upon. It should just change the defaults so that the op writers are used first, and are overridden only when SetContainerOut/Err are used.
Closes #78
> Write docker output to op writer

- driver/command/command.go
- driver/command/command_nix.go
- driver/command/command_nix_test.go
- driver/command/command_test.go
- driver/command/command_windows.go
Allow a runtime to explicitly set the command driver path, for situations where the driver is not on PATH. Porter is using this to make it easier to run tests in parallel, which doesn't play well with relying on global process values like environment variables.
I refactored the tests to use test cases, and add tests for the new code paths.
> Add explicit path to command driver

- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_test.go
- go.mod
When the image was already fully qualified the kubernetes driver was double appending the digest, e.g. foo/bar@sha:abc123@sha:abc123
> Fix appending digest to pod image

- driver/debug/debug.go
- driver/docker/docker.go
- driver/docker/docker_test.go
- driver/driver.go
- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
- driver/kubernetes/kubernetes_test.go
* Add IN_CLUSTER setting to the kubernetes driver.
The kubernetes driver defaults KUBECONFIG to ~/.kube/config when not set. This prevents the incluster configuration from being used.
To preserve the existing behavior, I have added IN_CLUSTER which indicates that ambient kubernetes configuration should be used. This is intended for when the cnab process is running inside a pod.
* Do not panic when setting driver config 
Use the go, Luke. Return errors instead of throwing a panic. This is a breaking change to the driver API, but we aren't at 1.0 and avoiding panics seems worth it.
I didn't see a way to add a test for in-cluster without a ton of extra test infra that we don't have right now. If we are concerned that incluster config needs a test case, we will need to add a docker registry …
> Support in-cluster k8s

- CONTRIBUTING.md
- README.md
I am renaming the default branch now, but this fixes our documentation to match.
> Rename master to main

- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
Currently we are silently ignoring errors when we cannot stream the pod logs. Which makes it super hard to troubleshoot why it didn't work, usually RBAC because you don't have get+list for pods/log. This prints a message in the logs indicating there was a problem and allows the job to finish.
> Log an error when kubernetes driver cannot stream logs

- Makefile
- azure-pipelines.yml
- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
- driver/kubernetes/kubernetes_test.go
- e2e-kind.sh
I am working on a Porter Operator that can run CNAB bundles using K8s CRDs. As part of that I had to make some changes to the Kubernetes driver to get real (not sample) bundles to work.
* Mount a persistent volume to share data: injected files and outputs, between the driver and the bundle job.
* Apply custom labels in the kubernetes driver
Allow the caller to specify additional labels to apply to resources created by the driver.
* Fix setting CLEANUP_JOBS
I had the if statement inverted... I've added a test to make sure it (and other settings) are correct.
* Remove requiredCompletions from k8s driver
The only value that ever makes sense for requiredCompletions is 1 because we aren't running parallel pods for the bundle job.
*  Improve defaulting for kubernetes driver
* When LimitCPU or …
> K8s driver improvements

- action/action.go
- action/action_test.go
When we go through the credentials and set them on the operation,
creating either environment variables or paths, take into account
credential.ApplyTo and do not error out when the credential is
required but doesn't apply to the current action.
This builds on top of my previous PR that added support for
credentials to use ApplyTo, where I had missed that we have duplicate
logic for validating credentials depending on the context (populating
the operation vs validating a credential set).
> Check credential.ApplyTo setting credentials on the operation

- .gitignore
- Makefile
- driver/kubernetes/kubernetes.go
- driver/kubernetes/kubernetes_integration_test.go
- driver/kubernetes/kubernetes_test.go
- e2e-kind.sh
- go.mod
- go.sum
- kind.config.yaml
This change introduces a setting to specify labels to be used for affinity for the Kubernetes driver.
The driver uses a PVC to copy input and output data between the driver and the job that runs the invocation image, In some cases there is a need to make sure that the job runs on the same node as another pod. For example, where the PVC is bound to the node running the driver with ReadWriteOnce access mode then the job running the invocation image must run on the same node as the pod creating the PVC, this change enables a client to set pod affinity appropriately.
To specify affinity with a pod the client should set the environment variable `AFFINITY_MATCH_LABELS`  with label name value pairs separated by whitespace. (e.g 'A=B X=Y'). These labels are used to set Pod Affinity constraints …
> Adds Pod Affinity to Kubernetes driver

- bundle/definition/schema.go
- bundle/definition/schema_test.go
* Adds support for params of type `object` in ConvertValue
(Original issue from Porter: https://github.com/getporter/porter/issues/1459)
> feat(schema.go): add support for params of object type in ConvertValue

- claim/claimstore.go
- claim/claimstore_test.go
I accidentally used TrimLeft instead of TrimPrefix when reading outputs from the claimstore. TrimLeft removes every character found in a string(cutset) from a string until it hits one that isn't found. TrimPrefix removes the specified string from the beginning of a string.
This can cause a bug where if any character found in the result id (a ulid) is the first character of the output's name, e.g. the result id has a 0 in it and the output name starts with 0, then extra characters from the output name are incorrectly trimmed as well, resulting in being unable to read that output back from the claimstore. 🤦‍♀️
> TrimPrefix and TrimLeft are NOT the same

- bundle/bundle.go
- bundle/bundle_test.go
* Fixes a bug wherein we weren't previously validating a parameter if we inherit the default.  Now we validate regardless of where we inherit the parameter from (e.g. an override or a default).
> fix(bundle.go): validate param regardless of if override or default

- bundle/bundle.go
- bundle/bundle_test.go
- bundle/parameters.go
- bundle/parameters_test.go
* Adds validation against default parameter values when defined
This can be used to catch validation errors at build-time, rather than runtime (which https://github.com/cnabio/cnab-go/pull/252 adds)
> feat(*): validate parameter default against its definition

- bundle/bundle.go
- bundle/outputs.go
- bundle/outputs_test.go
* Adds validation of a bundle's outputs, including validating that the default value (if provided) adheres to the output schema
> feat(outputs.go): add output validation

- bundle/definition/schema.go
- bundle/definition/schema_test.go
* Adds support for params of type array in the `ConvertValue` function
Builds on/depends on https://github.com/cnabio/cnab-go/pull/251
> feat(schema.go): add support for params of type array

- bundle/definition/validation.go
- bundle/definition/validation_test.go
- bundle/definition/validators.go
- go.mod
- go.sum
Background: 
The jsonschema library we use is not thread-safe: https://github.com/qri-io/jsonschema/issues/80. This prevents callers from validating and working with bundles concurrently.
Current Fix:
I made a fork of the latest version jsonschema and tweaked it so that it doesn't use package variables for everything, and uses a lock when it does access the global schema. I'm not sure if that is a solution that they will merge, still waiting on a reply. We are still using unreleased commits on docker repos so at least there is precedent. 😀 
The other changes you see in the PR are due to changes in the latest version of jsonschema.
I tried to fix this without changing jsonschema and wasn't successful. However I am not sure how we feel about using a fork of jsonschema when the patch may …
> Make validating a bundle thread-safe

- bundle/bundle.go
- bundle/bundle_test.go
This corrects a bug found in v0.20.0 where an optional parameter with no default set causes a validation error when the user does not specify the parameter. The error was:
```
invalid parameters: cannot use value: <nil> as parameter myparm: type should be string, got null
```
> Do not validate unspecified optional paramters

- go.mod
- go.sum
The PR fixing thread safety when registering a custom keyword has been merged so I'm removing the fork and going back to using the upstream repository.
See https://github.com/qri-io/jsonschema/pull/103
> Remove jsonschema fork

- claim/claim.go
This should have always been declared as a const, it's never supposed to change and it's just a string.
> Make the claims spec string a constant

- action/action_test.go
- action/example_install_test.go
- action/example_upgrade_test.go
- bundle/bundle.go
- claim/claim.go
- claim/claim_test.go
There isn't really a need to force people to handle (or ignore) an error from DefaultSchemaVersion. The default schema is hard coded and with tests and buildtime asserts, we know that it was set to a valid value.
We were already throwing a panic or ignoring the error anyway at runtime, so this is more of an assurance actually than what we had before.
> Change DefaultSchemaVersion to not return an error

- driver/docker/docker.go
- driver/docker/docker_integration_test.go
The op.Err field was added after the docker driver was first written. I noticed that when the caller of the docker driver doesn't set op.Err it causes a panic when we attach to the container's logs.
This fixes our defaulting of where we write errors so that we are never writing to a nil writer accidentally.
~It is based on #279 so I will rebase after that is merged.~
> Fix panic when op.Err is unset in Docker driver

- claim/result.go
- claim/result_test.go
- claim/testdata/result.json
Originally we were defining output metadata as a map[string]interface{}, and then just casting as needed any output metadata values to map[string]string. This worked fine when setting and then immediately checking values, because we set the metadata correctly to begin with.
When a result is unmarshaled though, the json decoder is unmarshaling the output metadata values as map[string]interface{} and this prevented the helper methods for reading the metadata from working.
I've updated the OutputMetadata type to be map[string]map[string]string so that we aren't relying on casts working, and to give the json decoder the hint it needs to initialize the types correctly.
> Fix unmarshal for claim results

- Makefile
- claim/claim_test.go
- driver/command/command_nix.go
- driver/command/command_nix_test.go
- driver/command/command_windows.go
- driver/docker/docker.go
- driver/docker/docker_integration_test.go
- driver/kubernetes/kubernetes_integration_test.go
However we were installing golangci-lint before (using their special install script) doesn't work on our CI anymore, or my local machine. I've updated to the most recent version of golangci-lint so that I could test it locally on my arm64 machine, and switch to using go install to install the tool.
I've also updated the code quick to get the `make lint` target passing again:
* Run go fmt over project
* Do not use testing.T helper from an anonymous function
> Fix installation of golangci-lint

- .github/workflows/build.yaml
I've converted our Azure DevOps Pipeline to a GitHub Workflow. I split out calling each target so that it's easier to find which step failed and repeat just failing steps in the build.
This is using the newer setup-go github action that has built in support for detecting which version of go to use based on the go.mod file and also caching downloaded go mods to speed up subsequent builds.
I've found that the github actions build much more quickly than pipelines and are easier for non-MSFT people to manage. Due to a quirk in how DevOps authenticates users, it was only this week that I was able to get my personal account to be able to log into DevOps to do things like re-try failed builds.
What do you think about adding this, seeing how it compares to our current pipeline (i.e. they both …
> Add github action that builds project

- fetch-schemas.go
Fixes #287
Everything is detailled in [this comment](https://github.com/cnabio/cnab-go/issues/287#issuecomment-1158289217), but, TLDR: The CI is using the `fetch-schemas` go program to download the latest schema data files from the cnab cdn. If it doesn't reply for some reason, the program is erasing the local version of the schema file by an empty file, which can cause 2 tests to fail:
- `TestClaimSchema`
- `TestBundleSchema`
This PR is adding a return when the fetch request fails, so that we don't write an empty file on the disk when it fails and so that the tests don't fail in that case.
The issue can be reproduced by running locally `go run fetch-schemas.go`. If you run this command before this PR, after turning off your internet connection (eg wifi), you will see that both files gets …
> fix: avoid erasing local schema if fetching schema from cdn.cnab.io fails

- driver/docker/client.go
- driver/docker/client_test.go
This enables the configuration of already instanciated DockerCli
> Export "BuildDockerClientOptions"

- bundle/definition/regexp.go
- bundle/definition/regexp_test.go
- bundle/definition/schema.go
- bundle/definition/validation_test.go
jsonschema specification has pattern validator for string parameters https://json-schema.org/draft/2020-12/json-schema-validation#name-contentencoding.
Add Pattern field to Schema to allow this validation.
> add pattern property to schema
